// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Event struct {
	ID             int64        `json:"id"`
	DiscordEventID string       `json:"discord_event_id"`
	GuildID        string       `json:"guild_id"`
	Title          string       `json:"title"`
	StartTime      time.Time    `json:"start_time"`
	ReminderSent   sql.NullBool `json:"reminder_sent"`
}

type Participant struct {
	EventID              int64          `json:"event_id"`
	UserID               int64          `json:"user_id"`
	TimeSinceLastVictory sql.NullString `json:"time_since_last_victory"`
}

type User struct {
	ID              int64          `json:"id"`
	DiscordID       string         `json:"discord_id"`
	Username        string         `json:"username"`
	Streak          sql.NullInt64  `json:"streak"`
	LastVictoryTime sql.NullString `json:"last_victory_time"`
}
