// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Boardgame struct {
	ID             int64          `json:"id"`
	Name           string         `json:"name"`
	Category       sql.NullString `json:"category"`
	MinPlayers     sql.NullInt64  `json:"min_players"`
	MaxPlayers     sql.NullInt64  `json:"max_players"`
	PlayTime       sql.NullInt64  `json:"play_time"`
	Description    sql.NullString `json:"description"`
	PreviousWinner sql.NullString `json:"previous_winner"`
	PlayedYet      sql.NullBool   `json:"played_yet"`
	LikedIt        sql.NullBool   `json:"liked_it"`
	RulesLink      sql.NullString `json:"rules_link"`
	LastUpdated    sql.NullTime   `json:"last_updated"`
}

type Event struct {
	ID             int64        `json:"id"`
	DiscordEventID string       `json:"discord_event_id"`
	GuildID        string       `json:"guild_id"`
	Title          string       `json:"title"`
	StartTime      time.Time    `json:"start_time"`
	ReminderSent   sql.NullBool `json:"reminder_sent"`
}

type Participant struct {
	EventID              int64          `json:"event_id"`
	UserID               int64          `json:"user_id"`
	TimeSinceLastVictory sql.NullString `json:"time_since_last_victory"`
}

type User struct {
	ID              int64          `json:"id"`
	DiscordID       string         `json:"discord_id"`
	Username        string         `json:"username"`
	Streak          sql.NullInt64  `json:"streak"`
	LastVictoryTime sql.NullString `json:"last_victory_time"`
}
