// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const addBoardGame = `-- name: AddBoardGame :one
INSERT INTO boardgames (name, category, min_players, max_players, play_time, description, previous_winner, played_yet, liked_it, rules_link, last_updated) 
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(name) DO UPDATE SET category=excluded.category, min_players=excluded.min_players, max_players=excluded.max_players, play_time=excluded.play_time, description=excluded.description, previous_winner=excluded.previous_winner, played_yet=excluded.played_yet, liked_it=excluded.liked_it, rules_link=excluded.rules_link, last_updated=CURRENT_TIMESTAMP
RETURNING id, name, category, min_players, max_players, play_time, description, previous_winner, played_yet, liked_it, rules_link, last_updated
`

type AddBoardGameParams struct {
	Name           string         `json:"name"`
	Category       sql.NullString `json:"category"`
	MinPlayers     sql.NullInt64  `json:"min_players"`
	MaxPlayers     sql.NullInt64  `json:"max_players"`
	PlayTime       sql.NullInt64  `json:"play_time"`
	Description    sql.NullString `json:"description"`
	PreviousWinner sql.NullString `json:"previous_winner"`
	PlayedYet      sql.NullBool   `json:"played_yet"`
	LikedIt        sql.NullBool   `json:"liked_it"`
	RulesLink      sql.NullString `json:"rules_link"`
}

func (q *Queries) AddBoardGame(ctx context.Context, arg AddBoardGameParams) (Boardgame, error) {
	row := q.db.QueryRowContext(ctx, addBoardGame,
		arg.Name,
		arg.Category,
		arg.MinPlayers,
		arg.MaxPlayers,
		arg.PlayTime,
		arg.Description,
		arg.PreviousWinner,
		arg.PlayedYet,
		arg.LikedIt,
		arg.RulesLink,
	)
	var i Boardgame
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.MinPlayers,
		&i.MaxPlayers,
		&i.PlayTime,
		&i.Description,
		&i.PreviousWinner,
		&i.PlayedYet,
		&i.LikedIt,
		&i.RulesLink,
		&i.LastUpdated,
	)
	return i, err
}

const addParticipant = `-- name: AddParticipant :exec
INSERT OR IGNORE INTO participants (event_id, user_id) VALUES (?, ?)
`

type AddParticipantParams struct {
	EventID int64 `json:"event_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) AddParticipant(ctx context.Context, arg AddParticipantParams) error {
	_, err := q.db.ExecContext(ctx, addParticipant, arg.EventID, arg.UserID)
	return err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (discord_event_id, guild_id, title, start_time, reminder_sent) VALUES (?, ?, ?, ?, 0)
RETURNING id, discord_event_id, guild_id, title, start_time, reminder_sent
`

type CreateEventParams struct {
	DiscordEventID string    `json:"discord_event_id"`
	GuildID        string    `json:"guild_id"`
	Title          string    `json:"title"`
	StartTime      time.Time `json:"start_time"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.DiscordEventID,
		arg.GuildID,
		arg.Title,
		arg.StartTime,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.DiscordEventID,
		&i.GuildID,
		&i.Title,
		&i.StartTime,
		&i.ReminderSent,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (discord_id, username) VALUES (?, ?)
RETURNING id, discord_id, username, streak, last_victory_time
`

type CreateUserParams struct {
	DiscordID string `json:"discord_id"`
	Username  string `json:"username"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.DiscordID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.Username,
		&i.Streak,
		&i.LastVictoryTime,
	)
	return i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, discord_id, username, streak, last_victory_time
FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.DiscordID,
			&i.Username,
			&i.Streak,
			&i.LastVictoryTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventByEventID = `-- name: GetEventByEventID :one
SELECT id, discord_event_id, guild_id, title, start_time, reminder_sent
FROM events
WHERE discord_event_id = ?
`

func (q *Queries) GetEventByEventID(ctx context.Context, discordEventID string) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventByEventID, discordEventID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.DiscordEventID,
		&i.GuildID,
		&i.Title,
		&i.StartTime,
		&i.ReminderSent,
	)
	return i, err
}

const getEventsForReminder = `-- name: GetEventsForReminder :many
SELECT id, discord_event_id, guild_id, title, start_time
FROM events 
WHERE start_time <= datetime('now', '+30 minutes') 
AND reminder_sent = 0
`

type GetEventsForReminderRow struct {
	ID             int64     `json:"id"`
	DiscordEventID string    `json:"discord_event_id"`
	GuildID        string    `json:"guild_id"`
	Title          string    `json:"title"`
	StartTime      time.Time `json:"start_time"`
}

// Finds events starting within the next 30 minutes (approx) that haven't been sent
func (q *Queries) GetEventsForReminder(ctx context.Context) ([]GetEventsForReminderRow, error) {
	rows, err := q.db.QueryContext(ctx, getEventsForReminder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventsForReminderRow
	for rows.Next() {
		var i GetEventsForReminderRow
		if err := rows.Scan(
			&i.ID,
			&i.DiscordEventID,
			&i.GuildID,
			&i.Title,
			&i.StartTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParticipants = `-- name: GetParticipants :many
SELECT users.discord_id
FROM participants
JOIN users ON users.id = participants.user_id
WHERE participants.event_id = ?
`

func (q *Queries) GetParticipants(ctx context.Context, eventID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getParticipants, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var discord_id string
		if err := rows.Scan(&discord_id); err != nil {
			return nil, err
		}
		items = append(items, discord_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByDiscordID = `-- name: GetUserByDiscordID :one
SELECT id, discord_id, username, streak, last_victory_time 
FROM users 
WHERE discord_id = ?
`

func (q *Queries) GetUserByDiscordID(ctx context.Context, discordID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByDiscordID, discordID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.Username,
		&i.Streak,
		&i.LastVictoryTime,
	)
	return i, err
}

const getUserLastVictory = `-- name: GetUserLastVictory :one
SELECT last_victory_time 
FROM users 
WHERE id = ?
`

func (q *Queries) GetUserLastVictory(ctx context.Context, id int64) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getUserLastVictory, id)
	var last_victory_time sql.NullString
	err := row.Scan(&last_victory_time)
	return last_victory_time, err
}

const getUserStreak = `-- name: GetUserStreak :one
SELECT streak 
FROM users 
WHERE id = ?
`

func (q *Queries) GetUserStreak(ctx context.Context, id int64) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, getUserStreak, id)
	var streak sql.NullInt64
	err := row.Scan(&streak)
	return streak, err
}

const incrementStreak = `-- name: IncrementStreak :exec
UPDATE users
SET streak = streak + 1, last_victory_time = datetime('now')
WHERE id = ?
`

func (q *Queries) IncrementStreak(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementStreak, id)
	return err
}

const markReminderSent = `-- name: MarkReminderSent :exec
UPDATE events 
SET reminder_sent = 1 
WHERE id = ?
`

func (q *Queries) MarkReminderSent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markReminderSent, id)
	return err
}

const recomendPlayedBoardGame = `-- name: RecomendPlayedBoardGame :many
SELECT name, description, rules_link
FROM boardgames
WHERE played_yet = 1 AND min_players <= ? AND max_players >= ?
ORDER BY RANDOM()
LIMIT 4
`

type RecomendPlayedBoardGameParams struct {
	MinPlayers sql.NullInt64 `json:"min_players"`
	MaxPlayers sql.NullInt64 `json:"max_players"`
}

type RecomendPlayedBoardGameRow struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	RulesLink   sql.NullString `json:"rules_link"`
}

func (q *Queries) RecomendPlayedBoardGame(ctx context.Context, arg RecomendPlayedBoardGameParams) ([]RecomendPlayedBoardGameRow, error) {
	rows, err := q.db.QueryContext(ctx, recomendPlayedBoardGame, arg.MinPlayers, arg.MaxPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecomendPlayedBoardGameRow
	for rows.Next() {
		var i RecomendPlayedBoardGameRow
		if err := rows.Scan(&i.Name, &i.Description, &i.RulesLink); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recomendUnplayedBoardGame = `-- name: RecomendUnplayedBoardGame :many
SELECT name, description, rules_link
FROM boardgames
WHERE played_yet = 0 AND min_players <= ? AND max_players >= ?
ORDER BY RANDOM()
LIMIT 4
`

type RecomendUnplayedBoardGameParams struct {
	MinPlayers sql.NullInt64 `json:"min_players"`
	MaxPlayers sql.NullInt64 `json:"max_players"`
}

type RecomendUnplayedBoardGameRow struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	RulesLink   sql.NullString `json:"rules_link"`
}

func (q *Queries) RecomendUnplayedBoardGame(ctx context.Context, arg RecomendUnplayedBoardGameParams) ([]RecomendUnplayedBoardGameRow, error) {
	rows, err := q.db.QueryContext(ctx, recomendUnplayedBoardGame, arg.MinPlayers, arg.MaxPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecomendUnplayedBoardGameRow
	for rows.Next() {
		var i RecomendUnplayedBoardGameRow
		if err := rows.Scan(&i.Name, &i.Description, &i.RulesLink); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recommendRandomBoardGame = `-- name: RecommendRandomBoardGame :many
SELECT name, description, rules_link
FROM boardgames
WHERE min_players <= ? AND max_players >= ?
ORDER BY RANDOM()
LIMIT 4
`

type RecommendRandomBoardGameParams struct {
	MinPlayers sql.NullInt64 `json:"min_players"`
	MaxPlayers sql.NullInt64 `json:"max_players"`
}

type RecommendRandomBoardGameRow struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	RulesLink   sql.NullString `json:"rules_link"`
}

func (q *Queries) RecommendRandomBoardGame(ctx context.Context, arg RecommendRandomBoardGameParams) ([]RecommendRandomBoardGameRow, error) {
	rows, err := q.db.QueryContext(ctx, recommendRandomBoardGame, arg.MinPlayers, arg.MaxPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecommendRandomBoardGameRow
	for rows.Next() {
		var i RecommendRandomBoardGameRow
		if err := rows.Scan(&i.Name, &i.Description, &i.RulesLink); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeEvent = `-- name: RemoveEvent :exec
DELETE FROM events
WHERE id = ?
`

func (q *Queries) RemoveEvent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, removeEvent, id)
	return err
}

const resetStreak = `-- name: ResetStreak :exec
UPDATE users
SET streak = 0
WHERE id = ?
`

func (q *Queries) ResetStreak(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, resetStreak, id)
	return err
}

const updateUserVictory = `-- name: UpdateUserVictory :exec
UPDATE users 
SET streak = streak + 1, last_victory_time = datetime('now') 
WHERE id = ?
`

func (q *Queries) UpdateUserVictory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateUserVictory, id)
	return err
}
