// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const addParticipant = `-- name: AddParticipant :exec
INSERT OR IGNORE INTO participants (event_id, user_id) VALUES (?, ?)
`

type AddParticipantParams struct {
	EventID int64 `json:"event_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) AddParticipant(ctx context.Context, arg AddParticipantParams) error {
	_, err := q.db.ExecContext(ctx, addParticipant, arg.EventID, arg.UserID)
	return err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (discord_event_id, guild_id, title, start_time, reminder_sent) VALUES (?, ?, ?, ?, 0)
RETURNING id, discord_event_id, guild_id, title, start_time, reminder_sent
`

type CreateEventParams struct {
	DiscordEventID string    `json:"discord_event_id"`
	GuildID        string    `json:"guild_id"`
	Title          string    `json:"title"`
	StartTime      time.Time `json:"start_time"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.DiscordEventID,
		arg.GuildID,
		arg.Title,
		arg.StartTime,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.DiscordEventID,
		&i.GuildID,
		&i.Title,
		&i.StartTime,
		&i.ReminderSent,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (discord_id, username) VALUES (?, ?)
RETURNING id, discord_id, username, streak, last_victory_time
`

type CreateUserParams struct {
	DiscordID string `json:"discord_id"`
	Username  string `json:"username"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.DiscordID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.Username,
		&i.Streak,
		&i.LastVictoryTime,
	)
	return i, err
}

const getEventByEventID = `-- name: GetEventByEventID :one
SELECT id, discord_event_id, guild_id, title, start_time, reminder_sent
FROM events
WHERE discord_event_id = ?
`

func (q *Queries) GetEventByEventID(ctx context.Context, discordEventID string) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventByEventID, discordEventID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.DiscordEventID,
		&i.GuildID,
		&i.Title,
		&i.StartTime,
		&i.ReminderSent,
	)
	return i, err
}

const getEventsForReminder = `-- name: GetEventsForReminder :many
SELECT id, discord_event_id, guild_id, title, start_time
FROM events 
WHERE start_time <= datetime('now', '+30 minutes') 
AND reminder_sent = 0
`

type GetEventsForReminderRow struct {
	ID             int64     `json:"id"`
	DiscordEventID string    `json:"discord_event_id"`
	GuildID        string    `json:"guild_id"`
	Title          string    `json:"title"`
	StartTime      time.Time `json:"start_time"`
}

// Finds events starting within the next 30 minutes (approx) that haven't been sent
func (q *Queries) GetEventsForReminder(ctx context.Context) ([]GetEventsForReminderRow, error) {
	rows, err := q.db.QueryContext(ctx, getEventsForReminder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventsForReminderRow
	for rows.Next() {
		var i GetEventsForReminderRow
		if err := rows.Scan(
			&i.ID,
			&i.DiscordEventID,
			&i.GuildID,
			&i.Title,
			&i.StartTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParticipants = `-- name: GetParticipants :many
SELECT users.discord_id
FROM participants
JOIN users ON users.id = participants.user_id
WHERE participants.event_id = ?
`

func (q *Queries) GetParticipants(ctx context.Context, eventID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getParticipants, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var discord_id string
		if err := rows.Scan(&discord_id); err != nil {
			return nil, err
		}
		items = append(items, discord_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByDiscordID = `-- name: GetUserByDiscordID :one
SELECT id, discord_id, username, streak, last_victory_time 
FROM users 
WHERE discord_id = ?
`

func (q *Queries) GetUserByDiscordID(ctx context.Context, discordID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByDiscordID, discordID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.Username,
		&i.Streak,
		&i.LastVictoryTime,
	)
	return i, err
}

const getUserLastVictory = `-- name: GetUserLastVictory :one
SELECT last_victory_time 
FROM users 
WHERE id = ?
`

func (q *Queries) GetUserLastVictory(ctx context.Context, id int64) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getUserLastVictory, id)
	var last_victory_time sql.NullString
	err := row.Scan(&last_victory_time)
	return last_victory_time, err
}

const getUserStreak = `-- name: GetUserStreak :one
SELECT streak 
FROM users 
WHERE id = ?
`

func (q *Queries) GetUserStreak(ctx context.Context, id int64) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, getUserStreak, id)
	var streak sql.NullInt64
	err := row.Scan(&streak)
	return streak, err
}

const incrementStreak = `-- name: IncrementStreak :exec
UPDATE users
SET streak = streak + 1, last_victory_time = datetime('now')
WHERE id = ?
`

func (q *Queries) IncrementStreak(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementStreak, id)
	return err
}

const markReminderSent = `-- name: MarkReminderSent :exec
UPDATE events 
SET reminder_sent = 1 
WHERE id = ?
`

func (q *Queries) MarkReminderSent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markReminderSent, id)
	return err
}

const updateUserVictory = `-- name: UpdateUserVictory :exec
UPDATE users 
SET streak = streak + 1, last_victory_time = datetime('now') 
WHERE id = ?
`

func (q *Queries) UpdateUserVictory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateUserVictory, id)
	return err
}

const resetStreak = `-- name: resetStreak :exec
UPDATE users
SET streak = 0
WHERE id = ?
`

func (q *Queries) resetStreak(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, resetStreak, id)
	return err
}
