// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddParticipant(ctx context.Context, arg AddParticipantParams) error
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAllUsers(ctx context.Context) ([]User, error)
	GetEventByEventID(ctx context.Context, discordEventID string) (Event, error)
	// Finds events starting within the next 30 minutes (approx) that haven't been sent
	GetEventsForReminder(ctx context.Context) ([]GetEventsForReminderRow, error)
	GetParticipants(ctx context.Context, eventID int64) ([]string, error)
	GetUserByDiscordID(ctx context.Context, discordID string) (User, error)
	GetUserLastVictory(ctx context.Context, id int64) (sql.NullString, error)
	GetUserStreak(ctx context.Context, id int64) (sql.NullInt64, error)
	IncrementStreak(ctx context.Context, id int64) error
	MarkReminderSent(ctx context.Context, id int64) error
	ResetStreak(ctx context.Context, id int64) error
	UpdateUserVictory(ctx context.Context, id int64) error
}

var _ Querier = (*Queries)(nil)
